### PR TITLE
Add colors to hex codes and built in css color names

### PR DESCRIPTION
**Pull request by runem**
This pull request introduces vscode color support for hex and color names in css.

screenshot 2019-02-23 at 11 51 12

### CODE REVIEW

**Comment by herberthobregon** [comment]
When will you upload this update? I look forward to it for a long time hahaha

**Comment by runem** [comment]
Sorry, I had completely forgotten all about this PR 🙈 At the time I actually did some more work on it, but concluded that I needed to build a bit more complex setup. The reason is that it's not enough just searching the code for regexes and colors like "red, blue, ...", because if you use the word "red" in a non-css-context, it will still show the color picker. 

What do you think about starting out with a MVP that only shows the color picker for hex colors? Then in the meantime I can think about how a more complex setup would look like  :-) 

Right away I'm thinking about two solutions:

 1. Find CSS contexts by searching for `css' ... '` and `<style>...</style>`. This might be fairly easy to implement.

 2. The underlying CSS analyzer (which I use for code completion/diagnostics) already understands CSS. I could extend it so that the vscode plugin could read the location of colors. This would be a bit more difficult to implement.

**Comment by herberthobregon** [comment]
Personally I **never** use colors like "_red_" or "_Blue_" in my styles, I always use their HEX
There is no point showing a `"red box"` next to a word that says explicitly `red` hahaha.

but if it is very valuable to add a `"red box"` to the for `#cd0000` that at first glance I do not know what color it is

I think `solution 1` is the best to have this feature in production

**Comment by runem** [comment]
This repo has been migrated to a mono-repo called [lit-analyzer](https://github.com/runem/lit-analyzer). I have build support for what we agreed on, and the feature will come out with the next release of [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin). Therefore I'll close this PR now :tada:

**Pull request closed without merging**
